name: Cypress Test in Docker

on:
  push:
    branches:
      - second
  pull_request:
  
    branches:
      - second

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Cypress tests in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/cypress_project:/e2e \
            -w /e2e \
            cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1 \
            sh -c "npm ci && npx cypress run --browser chrome --spec cypress/e2e/spec.cy.js"